# Generated by Django 4.2.3 on 2024-03-07 13:44

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Fixed discount amount', max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_percentage', models.IntegerField(blank=True, help_text='Discount percentage (0-100). Leave blank if using a fixed amount.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('valid_from', models.DateTimeField(default=datetime.datetime.now)),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('usage_limit', models.IntegerField(default=1, help_text='How many times this coupon can be used.', validators=[django.core.validators.MinValueValidator(1)])),
                ('times_used', models.IntegerField(default=0, editable=False, help_text='How many times this coupon has been used.')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart')),
            ],
        ),
    ]
